<<<<<<< HEAD
name: scrape revisions

on:
  schedule:
    - cron:  "0 0 * * *" # runs at 00:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner
    - name: setup python
      uses: actions/setup-python@v2
            with:
              python-version: 3.8 # python install
    - name: execute scraper # run ch-law-scraper.py to get the latest text
          run: |
            python ch-law-scraper.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git diff --color-words
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
=======

>>>>>>> 2003a4a3bca857334afa87a5d83455847e0c9bf8
